import imdb from "../../Assets/images/imdb_screenshot.png";
import socio from "../../Assets/images/socio_screenshot.png";
import myntra from "../../Assets/images/myntra_screenshot.png";
import passer from "../../Assets/images/passer_screenshot.png";
import bik from "../../Assets/images/bik_screenshot.png";
import expenses from "../../Assets/images/expenses_screenshot.png";
export const portFolioData = [
  {
    id: 1,
    img: imdb,
    projectName: "IMDB",
    desc: "This is clone of IMDB application , listing various movies, movie detail, rating , cast and more details...",
    projectLink: "https://pramodh-imdb-clone.netlify.app/",
    sourceCode: "https://github.com/NagaPramodh/IMDBClone",
  },
  {
    id: 2,
    img: socio,
    projectName: "Socio",
    desc: "This is Social Media Application for people and younger generations to express their feelings and emotions . They can come here Refresh themselves from any mental Pressure they have Here People can View Posts , create Post , like and comment .",
    projectLink: "https://socio-blog.netlify.app/",
    sourceCode: "https://github.com/NagaPramodh/Socio",
    status: "done",
  },
  // {
  //   id: 3,
  //   img: myntra,
  //   projectName: "Myntra",
  //   desc: "This App is clone of Myntra, Where Myntra being India's largest e-commerce store for fashion and lifestyle products",
  //   projectLink: "https://nagapramodh-myntra-clone.netlify.app/",
  //   sourceCode: "https://github.com/NagaPramodh/MyntraClone",
  //   status: "",
  // },
  {
    id: 4,
    img: passer,
    projectName: "Passer",
    desc: "A small application to track information about users working in Passer",
    projectLink: "https://passer-assignment-naga-pramodh.netlify.app/",
    sourceCode: "https://github.com/NagaPramodh/Passer",
    status: "",
  },
  {
    id: 5,
    img: bik,
    projectName: "Bik Landing Page",
    desc: "These are Bik.ai websites where user can see all the products and many other information regarding company ",
    projectLink: "https://bik.ai/",
    // sourceCode: "https://github.com/Varsha-Chaubey/employee-management-client",
    status: "",
  },
  {
    id: 6,
    img: expenses,
    projectName: "Expenses Tracker",
    desc: "This is a tracker for expenses,Where User can Filter , record and create Expenses",
    projectLink: "https://nagapramodh-expenses.netlify.app/",
    sourceCode: "https://github.com/NagaPramodh/Expenses-Tracker",
    status: "",
  },

  //   {
  //     id: 7,
  //     img: scard,
  //     projectName: " Shopping App",
  //     desc: "React project with Redux for state management. Thunk middleware for asynchronous actions. Added functionalities for cart manipulation",
  //     projectLink: "",
  //     sourceCode: "https://github.com/Varsha-Chaubey/shopingcard",
  //     status: "",
  //   },

  //   {
  //     id: 8,
  //     img: search,
  //     projectName: "Searchthing",
  //     desc: "It's a search engine using React and wikipedia search api.We can search any thing and see fined search result counts and can also check wikipedia of that perticular search.",
  //     projectLink: "",
  //     sourceCode: "https://github.com/Varsha-Chaubey/search-clone",
  //     status: "",
  //   },
  //   {
  //     id: 9,
  //     img: startup,
  //     projectName: "Start Up",
  //     desc: "A simple web app using React JS, Bootsrap and Javascript functionality.",
  //     projectLink: "",
  //     sourceCode: "https://github.com/Varsha-Chaubey/reactstartupwebsite",
  //     status: "",
  //   },
  //   {
  //     id: 10,
  //     img: pos,
  //     projectName: "POS App",
  //     desc: "A POS (Point of Sale) receipt generator built with ReactJS, featuring robust functionality. This application allows users to seamlessly generate receipts for transactions at a point of sale.",
  //     projectLink: "",
  //     sourceCode: "https://github.com/Varsha-Chaubey/pos-app",
  //     status: "Not Done Yet",
  //   },
  // {
  //     id:7,
  //     img:todo,
  //     projectName:"Todo List",
  //     projectLink:"",
  //     sourceCode:"",
  //     status:"Not Completed Yet",
  // },

  // {
  //     id:'',
  //     img:"",
  //     projectName:"",
  //     projectLink:"",
  //     sourceCode:"",
  //     status:"",
  // },
  // {
  //     id:'',
  //     img:"",
  //     projectName:"",
  //     projectLink:"",
  //     sourceCode:"",
  //     status:"",
  // },
  // {
  //     id:'',
  //     img:"",
  //     projectName:"",
  //     projectLink:"",
  //     sourceCode:"",
  //     status:"",
  // },
];
